In [6]:
import numpy as np
import pandas as pd

# Function to create train/val/test splits based on time series order
def make_splits(df, id_cols, date_col="date",
                frac_train=0.7, frac_val=0.15):
    # Sort by id_cols and date_col to ensure temporal order within each series
    df = df.sort_values(id_cols + [date_col]).copy()
    df["split"] = np.nan
    # Assign splits for each group
    for key, grp in df.groupby(id_cols):
        idx = grp.index.values
        n   = len(idx)
        # Determine split indices
        t1  = int(frac_train * n)
        t2  = t1 + int(frac_val   * n)
        # Assign splits
        df.loc[idx[:t1],  "split"] = "train"
        df.loc[idx[t1:t2], "split"] = "val"
        df.loc[idx[t2:],  "split"] = "test"
    return df

m5 = pd.read_csv("C:\\Users\\Bindhu\\Documents\\!Thesis\\m5_final\\Data\\m5_preprocessed_fe.csv", parse_dates=["date"])
m5 = make_splits(m5, id_cols=["id"])
m5.to_csv("C:\\Users\\Bindhu\\Documents\\!Thesis\\m5_final\\Data\\m5_final.csv", index=False)

C:\Users\Bindhu\AppData\Local\Temp\ipykernel_15640\3948468500.py:18: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'train' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[idx[:t1],  "split"] = "train"

In [7]:
m5

,id,item_id,dept_id,cat_id,store_id,state_id,sales,date,wday,year,...,weekofyear_nb,dayofyear_sin,dayofyear_cos,weekofyear_sin,weekofyear_cos,month_sin,month_cos,weekday_sin,weekday_cos,split
0,FOODS_1_010_WI_1_validation,FOODS_1_010,FOODS_1,FOODS,WI_1,WI,0.0,2011-01-29,1,2011,...,4,0.462383,0.886680,0.348202,0.937420,0.0,1.000000e+00,-0.974928,-0.222521,train
1,FOODS_1_010_WI_1_validation,FOODS_1_010,FOODS_1,FOODS,WI_1,WI,0.0,2011-01-30,2,2011,...,4,0.477536,0.878612,0.348202,0.937420,0.0,1.000000e+00,-0.781831,0.623490,train
2,FOODS_1_010_WI_1_validation,FOODS_1_010,FOODS_1,FOODS,WI_1,WI,0.0,2011-01-31,3,2011,...,5,0.492548,0.870285,0.456629,0.889657,0.0,1.000000e+00,0.000000,1.000000,train
3,FOODS_1_010_WI_1_validation,FOODS_1_010,FOODS_1,FOODS,WI_1,WI,0.0,2011-02-01,4,2011,...,5,0.507415,0.861702,0.456629,0.889657,0.5,8.660254e-01,0.781831,0.623490,train
4,FOODS_1_010_WI_1_validation,FOODS_1_010,FOODS_1,FOODS,WI_1,WI,0.0,2011-02-02,5,2011,...,5,0.522133,0.852864,0.456629,0.889657,0.5,8.660254e-01,0.974928,-0.222521,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
956495,HOUSEHOLD_2_389_CA_2_validation,HOUSEHOLD_2_389,HOUSEHOLD_2,HOUSEHOLD,CA_2,CA,11.0,2016-04-20,5,2016,...,16,0.949990,-0.312281,0.978556,-0.205979,1.0,6.123234e-17,0.974928,-0.222521,test
956496,HOUSEHOLD_2_389_CA_2_validation,HOUSEHOLD_2_389,HOUSEHOLD_2,HOUSEHOLD,CA_2,CA,12.0,2016-04-21,6,2016,...,16,0.944489,-0.328542,0.978556,-0.205979,1.0,6.123234e-17,0.433884,-0.900969,test
956497,HOUSEHOLD_2_389_CA_2_validation,HOUSEHOLD_2_389,HOUSEHOLD_2,HOUSEHOLD,CA_2,CA,15.0,2016-04-22,7,2016,...,16,0.938710,-0.344707,0.978556,-0.205979,1.0,6.123234e-17,-0.433884,-0.900969,test
956498,HOUSEHOLD_2_389_CA_2_validation,HOUSEHOLD_2_389,HOUSEHOLD_2,HOUSEHOLD,CA_2,CA,22.0,2016-04-23,1,2016,...,16,0.932655,-0.360771,0.978556,-0.205979,1.0,6.123234e-17,-0.974928,-0.222521,test
956499,HOUSEHOLD_2_389_CA_2_validation,HOUSEHOLD_2_389,HOUSEHOLD_2,HOUSEHOLD,CA_2,CA,3.0,2016-04-24,2,2016,...,16,0.926324,-0.376728,0.978556,-0.205979,1.0,6.123234e-17,-0.781831,0.623490,test

In [8]:
m5.columns

Index(['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'sales',
       'date', 'wday', 'year', 'sell_price', 'is_event', 'snap', 'day',
       'has_event2', 'lag_sales_1', 'lag_sales_7', 'lag_sales_14',
       'lag_sales_28', 'lag_sales_56', 'lag_sales_365', 'roll_mean_7',
       'roll_std_7', 'roll_mean_28', 'roll_std_28', 'roll_mean_56',
       'roll_std_56', 'roll_mean_365', 'roll_std_365', 'lag_price_1',
       'roll_price_7', 'price_change_1', 'cumulative_sales',
       'days_since_start', 'event_name_1_Chanukah End',
       'event_name_1_Christmas', 'event_name_1_Cinco De Mayo',
       'event_name_1_ColumbusDay', 'event_name_1_Easter',
       'event_name_1_Eid al-Fitr', 'event_name_1_EidAlAdha',
       'event_name_1_Father's day', 'event_name_1_Halloween',
       'event_name_1_IndependenceDay', 'event_name_1_LaborDay',
       'event_name_1_LentStart', 'event_name_1_LentWeek2',
       'event_name_1_MartinLutherKingDay', 'event_name_1_MemorialDay',
       'event_name_1_Mother's day', 'event_name_1_NBAFinalsEnd',
       'event_name_1_NBAFinalsStart', 'event_name_1_NewYear',
       'event_name_1_OrthodoxChristmas', 'event_name_1_OrthodoxEaster',
       'event_name_1_Pesach End', 'event_name_1_PresidentsDay',
       'event_name_1_Purim End', 'event_name_1_Ramadan starts',
       'event_name_1_StPatricksDay', 'event_name_1_SuperBowl',
       'event_name_1_Thanksgiving', 'event_name_1_ValentinesDay',
       'event_name_1_VeteransDay', 'event_type_1_Cultural',
       'event_type_1_National', 'event_type_1_Religious',
       'event_type_1_Sporting', 'dayofyear', 'weekday_nb', 'month_nb',
       'weekofyear_nb', 'dayofyear_sin', 'dayofyear_cos', 'weekofyear_sin',
       'weekofyear_cos', 'month_sin', 'month_cos', 'weekday_sin',
       'weekday_cos', 'split'],
      dtype='object')